- probert/network.py
This will claim that the device is unassociated when it may not be, being more detailed is significantly more invasive though, what do you think?
> do not crash if device does not support SIOCGIWESS

- probert/network.py
network-manager in snap form now writes its lease files to
/run/NetworkManager/dhcp, so add that directory when searching for DHCP
lease files.
> Add network-manager snap lease directory to lease file checks

- probert/network.py
Fix a stupid typo in an index variable name
Fixes: LP #1634430
> probert/network.py: fix typo in index variable name

- probert/network.py
- probert/prober.py
Probably too big a change for a single commit but never mind.
Highlights:
- Less inheritance, more composition (one now passes a "listener" to an
"observer" rather than subclassing the observer and overriding methods).
- There's now a way to have probert report a saved network configuration
rather than always probing the actual system
- The format of the saved network configuration has changed and now is
validated against a json schema
- The NetworkInfo class is gone, replaced by a Link class which is similar
but (imo) clearer and much more upfront about what data is calculated when
the class is instantiated vs what is derived later.
> almost total rewrite of Python parts of network probing

- debian/changelog
- debian/control
- probert/tests/fakes.py
This also drops the dependencies on python3-yaml, because it isn't actually used.
This will close #49.
> Modify debian/ packaging to rely on setup.py requirements

- probert/lvm.py
On systems with older lvm2 tools, the requested output may not be present but the command does not return a non-zero output; keep the type consistent by returning empty dict.
> lvm: return empty dict if pvs/vgs/lvs return no output

- probert/zfs.py
zfs_get_properties returns a dictionary, and the
caller added the result to an entry in the dictionary
resulting in nested keys like:
datasets:
rpool:
rpool:
{properties}
This patch removes the double key.
> zfs: remove double dataset names in dictionary

- .travis.yml
- Makefile
- probert/network.py
- probert/tests/test_prober.py
- probert/tests/test_storage.py
- probert/tests/test_utils.py
- probert/utils.py
- test-requirements.txt
- tox.ini
This adds a `make test` target that will execute tox. Tox in turn will
run py.test and flake8 against the repo.
Two fixes to the actual code to clean up flake8 issues, one change
to the network.py import around c-bindings so we do not have to build
the package for testing, and a few changes to test code to ensure
pylint passes. I choose this to speed up test/dev, rather than needing
deps and building.
Fixes #63
> testing: enable tox, travis, flake8, and pytest

- probert/lvm.py
- probert/tests/test_lvm.py
There were serveral return paths from lvm probing which returned a mix of None, [] or {}.
This branch ensures we always return a list.  Also add unittests for probert/lvm.py
> lvm: ensure probe returns type:list consistently

- probert/raid.py
Otherwise partitions of raids end up being reported as full RAID devices
and life is very confusing.
> probert.raid: only report devices with DEVTYPE=disk as raids

- probert/lvm.py
- probert/raid.py
- probert/storage.py
- probert/tests/helpers.py
- probert/tests/test_lvm.py
- probert/tests/test_utils.py
- probert/utils.py
A device's size in /sys/class/block/xxx/size is always in 512-byte
units so read and return the integer value * 512.[1]
- Drop reading from queue directory
- Rename read_sys_block_size -> read_sys_block_size_bytes
- Add unittests
1. https://github.com/torvalds/linux/blob/6f0d349d922ba44e4348a17a78ea51b7135965b1/include/linux/blkdev.h#L1026
Fixes: #74
> probert/utils: Don't use logical_sector_size for calculations

- probert/_rtnetlinkmodule.c
new_link is NULL in the v2 callback for a DEL action
> fix segfault when a netdev disappears

- debian/control
- debian/probert-common.install
- debian/probert-network.install
- debian/probert-storage.install
In other projects we maintain branches with just the ubuntu packaging. This allows us to merge new upstream snapshots quickly and maintain release deltas in these branches if needed.
> Add packaging fixes to debian dir

- probert/multipath.py
- probert/tests/test_multipath.py
Use a non-whitespace separator when generating output from
multipathd, then tokenize the output using the separator, preserving
whitespace in the field, serial, for example.
> multipath: use non-whitespace to split output

- probert/dmcrypt.py
- probert/filesystem.py
- probert/lvm.py
- probert/raid.py
- probert/storage.py
- probert/tests/test_lvm.py
- probert/utils.py
https://bugs.launchpad.net/subiquity/+bug/1868109 reports a crash
stemming from a block device that has no MAJOR in udev. I'm not sure
what that represents, but crashing probably isn't the correct response.
Ignore such devices instead.
> cope with block devices with no MAJOR in udev

- probert/lvm.py
- probert/tests/test_lvm.py
vgscan --mknodes has a bug which creates block device nodes for any
entry in dmsetup table if it doesn't exist yet.  This breaks the
assumption that /dev/mapper entries are symlinks created by udev.
Until upstream RHBZ: #1828617 is resolved do not use --mknodes.
> lvm: don't use vgscan --mknodes

- probert/raid.py
Example output:
```json
ubuntu@201903-26908-Pearl-VROC:~/probert$ PYTHONPATH=. ./bin/probert --storage | jq .storage.raid
{
"/dev/md125": {
"DEVLINKS": "/dev/md/subvol_0 /dev/disk/by-id/md-uuid-249587ce:98f591fa:7effa7d1:4639841a",
"DEVNAME": "/dev/md125",
"DEVPATH": "/devices/virtual/block/md125",
"DEVTYPE": "disk",
"MAJOR": "9",
"MD_CONTAINER": "/dev/md/imsm0",
"MD_DEVICES": "2",
"MD_DEVICE_ev_nvme0n1_DEV": "/dev/nvme0n1",
"MD_DEVICE_ev_nvme0n1_ROLE": "0",
"MD_DEVICE_ev_nvme1n1_DEV": "/dev/nvme1n1",
"MD_DEVICE_ev_nvme1n1_ROLE": "1",
"MD_DEVNAME": "subvol_0",
"MD_LEVEL": "raid0",
"MD_MEMBER": "0",
"MD_UUID": "249587ce:98f591fa:7effa7d1:4639841a",
"MINOR": "125",
"SUBSYSTEM": "block",
"TAGS": ":systemd:",
"UDISKS_MD_CONTAINER": "/dev/md/imsm0",
"UDISKS_MD_DEVICES": "2", …
```
> include imsm containers in "raids"

- probert/network.py
apparently not all network devices have DEVTYPE in their uevent
> fix network probing

- probert/_nl80211module.c
- probert/_rtnetlinkmodule.c
Implement PY_SSIZE_T_CLEAN.  It requires that, instead of using int for various
buffer lengths, that we instead use ssize_t.  While there are several calls to
PyArg_ParseTuple and Py_BuildValue family functions, only this one seems to be
passing around a length value.
Verified by running against Jammy with python 3.10, and console-conf in
dry-run, on hardware that has a wireless network interface.
(LP: #1964571)
> PY_SSIZE_T_CLEAN & python 3.10 compatibility

- probert/os.py
- probert/storage.py
- probert/tests/test_storage.py
Exclude 'os' from the default storage probes.
Add a 'defaults' keyword, which can be used in a set with 'os' to get both the
defaults and the 'os' result.
> storage: exclude os from the default probe set

- probert/raid.py
For https://bugs.launchpad.net/ubuntu/+source/curtin/+bug/1970116
Cherry-pick 79b2c34b4337ce7d11c771f3cb3868b90cae0c3f
> Do not recognize partitions of RAIDs as full RAIDs

- probert/bcache.py
- probert/dasd.py
For https://bugs.launchpad.net/subiquity/+bug/1972834.
> use sane_block_devices when looking for dasds

- probert/storage.py
- probert/tests/test_storage.py
- test-requirements.txt
Subiquity installs are now failing when it tries to hand the probe results to curtin and they contain partitions that are on a loopback device.  Curtin tries to associate this partition to a disk, and that disk doesn't exist because it has been filtered from the results.
So also filter those partitions.
> storage: skip partitions on device we are skipping

- probert/raid.py
In probing arrays, if the array is inactive then udev does not report an MD_LEVEL value for the array.  This was causing a KeyError when probe() tried to add the raidlevel key for the device.  This change checks see if MD_LEVEL exists before it tries to access it.
> storage: handle inactive arrays, which don't have a RAID level

- probert/filesystem.py
- probert/tests/test_filesystem.py
When `ID_PART_ENTRY_SIZE` is defined, the size of the swap is defined as `512 * ID_PART_ENTRY_SIZE`.
However, when the value is given as a string, the result is ... 512 times the string ; which is hardly what we expect.
Fixed by converting the string to an integer before applying the multiplication.
I noticed the issue when troubleshooting https://bugs.launchpad.net/subiquity/+bug/2002413
> swap: fix calculation of swap size

- probert/filesystem.py
- probert/tests/test_utils.py
- probert/utils.py
enhance the command runner run() with the following properties:
1) stdout/stderr/return code always logged, pass or fail
2) clear output distinction - no ambiguity between other logging and
command output, and a discernable difference between no output on
a channel versues empty lines
3) like before, returns stdout or None for pass/fail
I see this as something of a template for what good command output logging could look like, so I specifically want nitpicky type feedback before I copy it to other places.
Attached is an example of pass and fail output logging using this, as captured in Subiquity.
[probert-log-updates.log](https://github.com/canonical/probert/files/11022686/probert-log-updates.log)
> Fix stderr logging of resize tools

- probert/filesystem.py
By default, ntfsresize shows a progress indicator even if the output is not a terminal. This leads to very verbose logging, as in:
```
2023-04-14 10:29:25,542 DEBUG probert.utils:49   0.03 percent completed
2023-04-14 10:29:25,542 DEBUG probert.utils:49   0.04 percent completed
2023-04-14 10:29:25,543 DEBUG probert.utils:49   0.06 percent completed
2023-04-14 10:29:25,543 DEBUG probert.utils:49   0.07 percent completed
2023-04-14 10:29:25,543 DEBUG probert.utils:49   0.09 percent completed
2023-04-14 10:29:25,543 DEBUG probert.utils:49   0.10 percent completed
2023-04-14 10:29:25,544 DEBUG probert.utils:49   0.12 percent completed
2023-04-14 10:29:25,544 DEBUG probert.utils:49   0.13 percent completed
2023-04-14 10:29:25,544 DEBUG probert.utils:49   0.15 percent completed
2023-04-14 …
```
> filesystem-sizing: disable progress indicator on ntfsresize

- debian/control
- probert/tests/helpers.py
- probert/tests/test_dasd.py
- probert/tests/test_lvm.py
- probert/tests/test_multipath.py
- probert/tests/test_prober.py
- probert/tests/test_storage.py
- probert/tests/test_utils.py
- test-requirements.txt
I have prepared a branch to make probert storage asyncio-ready (and enable parallelism if desired - which makes things faster).
Sadly, testtools does not have support for something like `IsolatedAsyncioTestCase` (yet?).
Since, we're not using anything special from testtools or mock, we can safely move to using the testing tools from the standard library instead.
> tests: use unittest instead of testtools and mock

- bin/probert
- probert/bcache.py
- probert/dasd.py
- probert/dmcrypt.py
- probert/filesystem.py
- probert/lvm.py
- probert/mount.py
- probert/multipath.py
- probert/os.py
- probert/prober.py
- probert/raid.py
- probert/storage.py
- probert/tests/test_dasd.py
- probert/tests/test_filesystem.py
- probert/tests/test_lvm.py
- probert/tests/test_multipath.py
- probert/tests/test_os.py
- probert/tests/test_prober.py
- probert/tests/test_storage.py
- probert/utils.py
- probert/zfs.py
The code does not enforce the use of parallelism, but running probes in parallel lead to a sizable speedup in my tests.
During testing, I ran into one issue with parallelism: sometimes the mount probe finds a filesystem mounted under /var/lib/os-prober/mount. This is where os-prober temporarily mounts partitions while it is running.
I reported a bug and opened a PR upstream: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1034485
In the meantime, I added a patch in this series to make sure os-prober runs in a private mount namespace.
> Move storage code to asyncio - optionally enable parallelism for probes

- probert/filesystem.py
- probert/storage.py
- probert/tests/test_filesystem.py
In GPT partitions, the PartitionName field is stored as a utf-16 string. For some reason though, in udev, the value is not converted from utf-16 to utf-8. Instead, the MSB is dropped and the LSB is kept. e.g.,
* letter A in UTF-16 is 0x0041. It becomes 0x41 (which is letter A)
* e-ecute (é) in UTF-16 is 0x00E9. It becomes 0xE9
* euro sign (€) in UTF-16 is 0x20AC. It becomes 0xAC
* pound sign (£) in UTF-16 is 0x00A3. It becomes 0xA3
In the above examples, only the letter A results in a valid UTF-8 character.
When using pyudev, the values are all expected to be decodable using the system's default encoding.
In probert, it can result in a crash when iterating over all the properties of a block device, that are mapped by pyudev.
To work around the issue, we now stop iterating over all the …
> Fix crash when PARTNAME is invalid utf-8

- probert/mount.py
I want to make subiquity a bit more subtle in how it handles the install media, which means it needs to understand the pre-existing mounts in the live session a little better. Casper creates some mounts that are pretty hard to decode from the information we save already, but if we record the device major/minor we can pretty reliably map that to a partition.
> record device maj:min in mount data

- probert/nvme.py
- probert/storage.py
Block probing now includes a new key called "nvme" which contains a Udev dump of the `SUBSYSTEM="nvme"` devices. Each entry corresponds to a NVMe controller and has all the properties we need to find out if drives using this NVMe controller are "local", "over TCP" or soemthing else.
> Also return info about NVMe devices

- setup.py
It does not make sense for install_requires to specify a version of jsonschema that is over 7 years old.
> do not pass strict versions to install_requires

- bin/probert
- debian/changelog
- debian/control
- debian/probert-firmware.install
- probert/firmware.py
- probert/prober.py
- probert/tests/test_prober.py
For NVMe/TCP, we will want Subiquity to determine if booting with the boot FS on remote-storage is supported by the firmware. So far, it looks like we might need to rely on the "bios-vendor" value so we now expose this information from probert.
Since firmware related information should not change between two different probert invocations now make it part of a "firmware" prober, that Subiquity should realistically call only once.
> Add way to probe firmware information

- probert/network.py
- probert/tests/test_network.py
Our `_nl80211` Python module sometimes crashes. Although, we haven't managed to reproduce the crash yet, we have seen occurrences of the crash on the desktop installer, e.g., https://bugs.launchpad.net/ubuntu/+source/probert/+bug/2071620
That said, it looks like the desktop installer does not really need the `_nl80211` module. It currently interacts with NetworkManager directly.
Let's make it optional to use the `_nl80211` module. To disable its use, one can now pass `with_wlan_observer=True` when instantiating the UdevObserver class.
> Make it optional to use the WLAN listener

- probert/_nl80211module.c
Reading the ieee80211 implementation in the kernel [1], it looks like information elements can have a length of up-to 0xFF. Because we were working with signed chars (well, depends on the compilation flags) in `nl80211_get_ie`, we could interpret the length as a negative value.
The length is later used to "jump" to the next IE. So if we are interpreting it as a negative value, we're definitely going to read memory that we should not be reading.
I suppose this is what happens in https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/2060894
[1] https://github.com/torvalds/linux/blob/1a9239bb4253f9076b5b4b2a1a4e8d7defd77a95/include/linux/ieee80211.h#L4841-L4845
> nl80211: handle information elements with length > 0x7F

- probert/_nl80211module.c
In some situations (details are unknown), the SSID information element can be missing for a given network. This lead to a NULL pointer dereference when trying to extract the SSID, causing a crash of the Python process.
Ensure we ignore the SSID rather than crashing.
[LP: #2104087](https://launchpad.net/bugs/2104087)
> network: handle missing SSID information element

- probert/_nl80211module.c
- probert/_rtnetlinkmodule.c
The subiquity CI is a bit pedantic and will fail if probert builds with warnings.
Let's address the warnings that it complains about.
```
probert/_rtnetlinkmodule.c: In function ‘cb’:
probert/_rtnetlinkmodule.c:416:39: error: passing argument 1 of ‘nl_object_get’ from incompatible pointer type [-Wincompatible-pointer-types]
416 |                         nl_object_get(candidate);
|                                       ^~~~~~~~~
|                                       |
|                                       struct rtnl_link *
In file included from /usr/include/libnl3/netlink/netlink.h:29,
from /usr/include/libnl3/netlink/cache.h:9,
from probert/_rtnetlinkmodule.c:7:
/usr/include/libnl3/netlink/object.h:30:47: note: expected ‘struct nl_object *’ but argument is of type ‘struct rtnl_link …
```
> Fix warnings from recent patches

- probert/network.py
This main block in network.py is not exposed by the "probert" CL tool. However it can be used as an example to test some of the nl80211 code.
It has been broken for years, let's at least fix the use of undefined variables.
> network: fix use of undefined variables in main block
