canonical/probert

- probert/_rtnetlinkmodule.c
- probert/network.py
And include the scope in that information.
This breaks API a bit, I'll be changing subiquity to match in a moment.
> store all information about an address in an object

- probert/network.py
Just doing the PR so that people see this, I'm going to merge it straight away.
> fix computation of .type for devices that appear and are immediately renamed

- probert/network.py
Actually refresh bond state of slaves and masters, on link changes.
> Bond refresh

- setup.py
Adding install_requies to be able to pick up runtime requirements at install time.
> added install_requires to setup.py

- probert/filesystem.py
And swap, because we need to mount that too.
> Only report fs info for devices libblkid considers filesystems

- probert/multipath.py
Handle parsing of mpath command output so we don't stack trace if the output doesn't conform.
> multipath: considate extraction, handle missing elements in output

- probert/storage.py
MSDOS _extended_ partitions are rather annoying; but they are a reality; thus we need more information on the partition layout on block devices.  Fortunately, sfdisk has recently added a nice --json  and --bytes
output which is exactly the sort of output we can use.
> blockdev: use sfdisk to extract partition information if present.

- probert/_rtnetlinkmodule.c
I was testing the live server installer for 18.04.3, just fooling
around, when I noticed that if I disabled and reenabled an interface,
subiquity didn't notice; the button on the network screen stubbornly
stayed at "[ Continue without networking ]". After staring at debug
output and the libnl3 source for a good long while, I figured out what
was going on, and it was very related to the bug I fixed in subiquity
recently where subiquity didn't notice the default route going away.
That bug was caused by the fact that when an interface goes down, there
are not netlink notifications for each route on that interface going
away.
For libnl3's route cache, this means that the default route hangs around
in the cache. When the interface comes back up and the route is added
again, libnl3 doesn't …
> remove routes for an interface from libnl's cache when it does down

- probert/network.py
I did this while testing some subiquity wifi improvements
> have dry run mode supply some fake scan results

- probert/network.py
add a new DEV_TYPE 'can' for arptype 280 (canX interfaces)
> Support CAN interfaces (LP: #1890397)

- debian/rules
> d/rules: fix dh_missing; general cleanup

- probert/dasd.py
- probert/tests/test_dasd.py
* Report more information (including ECKD vs FBA) about "real" dasds
* Include dasds-passed-via-virtio in the set of dasds.
> dasd probing enhancements

- probert/network.py
Previously this data was added when the first NL80211 message was seen
for a nic but it seems no such events are sent for mac80211_hwsim NICs
which otherwise would be useful for testing.
This change also conceivably fixes some bugs where a UI processes a wlan
NIC before the first NL80211 message is seen for it, but I've never had
any reports of that.
> add wlan data to wlan devices as they are created

- probert/filesystem.py
This scenario comes up with BitLocker.
> Allow usage == crypto as a filesystem

- probert/raid.py
> raid: invoke mdadm --detail directly now that the udev does not membership info

- .github/workflows/build.yaml
- requirements.txt
* update workflow for above versions
* update pyudev in requirements.txt for py3.10 fixes to collections
> workflows: python 3.8/3.9/3.10

- probert/bcache.py
- probert/dasd.py
Cherry-pick #117 to the stable branch.
LP: #1972834
> Merge fix for block_device filtering

- LICENSE
- bin/probert
- debian/copyright
- probert/__init__.py
- probert/bcache.py
- probert/dasd.py
- probert/dmcrypt.py
- probert/filesystem.py
- probert/log.py
- probert/lvm.py
- probert/mount.py
- probert/multipath.py
- probert/network.py
- probert/nvme.py
- probert/os.py
- probert/prober.py
- probert/raid.py
- probert/storage.py
- probert/tests/helpers.py
- probert/tests/test_filesystem.py
- probert/tests/test_os.py
- probert/zfs.py
- setup.py
Update LICENSE, headers and metadata in debian/copyright and setup.py
> Relicense from AGPLv3+ to GPLv3

- LICENSE
- bin/probert
- debian/copyright
- probert/__init__.py
- probert/bcache.py
- probert/dasd.py
- probert/dmcrypt.py
- probert/filesystem.py
- probert/log.py
- probert/lvm.py
- probert/mount.py
- probert/multipath.py
- probert/network.py
- probert/prober.py
- probert/raid.py
- probert/storage.py
- probert/tests/helpers.py
- probert/zfs.py
- setup.py
Note that the core/jammy branch is one I just created from the commit the core22 snap is built from.
> Relicense core/jammy to GPL3 only

- .github/workflows/build.yaml
- .github/workflows/cla-check.yaml
- probert/tests/helpers.py
* drop usage of imp (like curtin 1667812bc4b2393776a8ee32d558b6ffe37d3b11)
* fix cla-check
* overhaul build - actually build, run on noble
> unittest / workflows fixes

- probert/_nl80211module.c
- probert/network.py
- probert/tests/test_network.py
Make it possible on noble to disable the use of our nl80211 module written in C.
Also add two fixes to the C code, that are known to either cause crashes, busy loops or worse.
> Backport network fixes to ubuntu/noble.
